### ISSUE TITLE
npm test issues | tests not passing

### ISSUE THREAD

**Issue by fastmode** [learn-co-students/js-tictactoe-rails-api-v-000#297]
When testing with 'npm test' (learn) in the Terminal while using ES6 "const" or "let", most test will fail.  Would be good to update npm test to allow these test to pass or alert the users that these test will fail if you use ES6.  When running test within the browser using "mocha.run" these test successfully pass.  

Quick way to check this, is to change any of your initial 'tictactoe.js' file declared variables to const or let, then run npm test in Terminal.  You will see that test will fail.  Now run test utilizing the /test/fixtures/index-test.html file provided in repo and use mocha.run() to execute test.  The tests will pass.

**Comment by DanielSeehausen** [comment]
Hi @fastmode! 

Thank you for raising the issue.
These tests are indeed compatible with ES6 syntax (to see it in action, attempt changing one of your functions to var x = () => {})
I believe there is a misunderstanding re: scoping constraints of `const`/`let` vs. `var` here! 

Raising issues on GitHub should be reserved for problems with the curriculum — not difficulties solving a lab.

The issue here appears to be with your own code. If the error messages in the test suite are not providing enough information for you to diagnose the problem, try the following three things:

Run your code as it is intended to be run. That is, don't simply rely on the test suite to check the functionality of your code — check it yourself! For Ruby code, add some lines to the bottom of the file that call your methods and output verifiable information to the terminal. For Sinatra or Rails applications, fire up your local server and try executing the same actions that the test suite is failing to complete. For JavaScript code, open up your browser's JS console, paste in your code, and play around with your functions and variables.
Use Pry to poke around your Ruby (or Sinatra), Rails, or JavaScript code step-by-step. Check that the values of particular variables are what you expect them to be at various points throughout the program's execution.
Use the Ask a Question (AAQ) feature, where the Technical Coaches (on supported tracks) and fellow community members can help you figure it out. For some tips on how to take full advantage of AAQ, check out this helpful article in the Learn Help Center.
If, after reviewing your code and consulting AAQ, you still feel that this is an issue with the curriculum itself, please reopen the issue and provide more detail about why it's a curriculum issue, the steps needed to reproduce the issue, and any additional relevant information about your development environment (local or IDE).

Thanks! 💙
