### ISSUE TITLE
tests pass in browser but not by learn

### ISSUE THREAD

**Issue by kevinYCKim33** [learn-co-students/js-tictactoe-rails-api-v-000#319]
when I do mocha.run() in the test browser console, all my tests pass, but when I do npm test or learn test, several tests fail.

**Comment by DanielSeehausen** [comment]
Hi @kevinYCKim33! 

Thank you for raising the issue. Without more information, we are unable to help you at this time. We have seen students run into a common error here that may be the problem:

Double check your usage of `const`/`let`. While this lab is compatible with ES6 syntax, their scoping restrictions may be causing you problems. 

Raising issues on GitHub should be reserved for problems with the curriculum — not difficulties solving a lab.

The issue here appears to be with your own code. If the error messages in the test suite are not providing enough information for you to diagnose the problem, try the following three things:

Run your code as it is intended to be run. That is, don't simply rely on the test suite to check the functionality of your code — check it yourself! For Ruby code, add some lines to the bottom of the file that call your methods and output verifiable information to the terminal. For Sinatra or Rails applications, fire up your local server and try executing the same actions that the test suite is failing to complete. For JavaScript code, open up your browser's JS console, paste in your code, and play around with your functions and variables.
Use Pry to poke around your Ruby (or Sinatra), Rails, or JavaScript code step-by-step. Check that the values of particular variables are what you expect them to be at various points throughout the program's execution.
Use the Ask a Question (AAQ) feature, where the Technical Coaches (on supported tracks) and fellow community members can help you figure it out. For some tips on how to take full advantage of AAQ, check out this helpful article in the Learn Help Center.
If, after reviewing your code and consulting AAQ, you still feel that this is an issue with the curriculum itself, please reopen the issue and provide more detail about why it's a curriculum issue, the steps needed to reproduce the issue, and any additional relevant information about your development environment (local or IDE).

Thanks! 💙
